spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none

sites:
  - url: https://nizhny800.ru/
    name: nizhny800

connect:
  useragent: Mozilla / 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit / 537.36 (KHTML, как Gecko) Chrome / 81.0.4044.92 Safari / 537.36
  referrer: http://www.google.com

url: /admin